### PR TITLE
Integration of mock sensor type

### PR DESCRIPTION
**Pull request by Honry**
Fixes part of https://github.com/w3c/sensors/issues/378

***
<a href="https://pr-preview.s3.amazonaws.com/Honry/ambient-light/pull/54.html" title="Last updated on Jan 25, 2019, 7:22 AM UTC (ea4a2e3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ambient-light/54/d6acf93...Honry:ea4a2e3.html" title="Last updated on Jan 25, 2019, 7:22 AM UTC (ea4a2e3)">Diff</a>

### CODE REVIEW

**Comment by Honry** [comment]
@anssiko and all, PTAL. Thanks!

**Comment by anssiko** [comment]
Seems good to me.

@reillyeon please take a look too.

**Comment by anssiko** [comment]
Yes, partial enum is still not a thing. The topic been discussed in this group earlier https://github.com/w3c/sensors/issues/22#issuecomment-110073878

**Comment by Honry** [comment]
@anssiko, @reillyeon, many thanks for your review!
Seems the [enum](https://w3c.github.io/ambient-light/#mock-ambient-light-sensor-type) is still non linkable, any idea?

**Comment by anssiko** [comment]
@Honry `bikeshed update --anchors` will fix it, see https://tabatkins.github.io/bikeshed/#cli-update

The `--anchors` flag will update your local Bikeshed "anchor data" to the latest that includes "ambient-light" enum, see https://github.com/tabatkins/bikeshed-data/blob/master/data/anchors/anchors-am.data#L1

Please create a PR to update this spec and also update the other PRs for other concrete specs accordingly.

**Comment by anssiko** [comment]
@Honry since the other PRs did not have any enum linking errors, you probably updated the anchor data between the builds?

**Comment by Honry** [comment]
Oh, I find the root cause now, I did't update the anchor data between the builds, I will do that for all PRs.

**Pull request merged**
