### PR TITLE
Permissions integration tweaks

### PR DESCRIPTION
**Pull request by anssiko**
Related https://github.com/w3c/permissions/issues/307

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ambient-light/pull/71.html" title="Last updated on Dec 3, 2021, 10:31 AM UTC (56b31bf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ambient-light/71/9ccf79e...56b31bf.html" title="Last updated on Dec 3, 2021, 10:31 AM UTC (56b31bf)">Diff</a>

### CODE REVIEW

**Comment by anssiko** [comment]
cc @miketaylr @rakuco

**Review by miketaylr — APPROVED** [review]
LGTM

**Review by reillyeon — APPROVED** [review]

**Comment by rakuco** [comment]
A bit late to the party, but as someone more familiar with ReSpec than Bikeshed, I don't understand why moving from `[=powerful feature/name=]` to `[=name=]` + custom anchor is beneficial, it seems to achieve the same thing with more steps. Am I missing something obvious?

**Comment by anssiko** [comment]
When I saw the error `No 'dfn' refs found for 'name' with for='['powerful feature']'` it reminded me the integration of the webref data in bikeshed is still WIP tabatkins/bikeshed#1761

**Comment by rakuco** [comment]
Hmm, interesting. I don't see it being defined in bikeshed's own `spec-data/`, but CI passed in #70 and when I did the same thing locally and invoked bikeshed via `curl` the resulting HTML file also looked fine. Do you remember what triggered the error you mentioned?

**Comment by anssiko** [comment]
I took a closer look at this. I was using a bikeshed build from [0f512236a209aff4eec2cbb81a75c709efa14aee](https://github.com/tabatkins/bikeshed/commit/0f512236a209aff4eec2cbb81a75c709efa14aee) with spec-data from 15 Nov and was able to reproduce. However, I just did the usual `bikeshed update` and now this resulted in a clean spec build thanks to this particular reference now appearing in the generated local data file `spec-data/anchors/anchors-na.data` (names autogen too, so yours might differ).

I probably should stop using my local bikeshed build and move to use whatever is hosted... old habits :)

Fix https://github.com/w3c/ambient-light/pull/74 PTAL. Thanks for paying attention to this detail!

**Comment by rakuco** [comment]
Thanks for double-checking this. TIL there's `spec-data/readonly/anchors` and `spec-data/anchors`, and `bikeshed update` apparently updates the latter o_O

**Pull request merged**
